# Generated by Django 5.0.2 on 2024-03-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates_app', '0002_alter_candidate_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='id',
            new_name='idd',
        ),
    ]
