# Generated by Django 5.0.2 on 2024-04-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates_app', '0003_candidate_exam_candidate_exam_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='exam_number',
        ),
    ]
