# Generated by Django 5.0.2 on 2024-03-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_receptionstaff_id_alter_superadmin_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receptionstaff',
            old_name='id',
            new_name='idd',
        ),
        migrations.RenameField(
            model_name='superadmin',
            old_name='id',
            new_name='idd',
        ),
    ]
