# Generated by Django 5.0.2 on 2024-05-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_visitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='phone',
        ),
        migrations.AddField(
            model_name='visitor',
            name='who_to_visit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
