# Generated by Django 5.0.2 on 2024-05-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_rename_first_name_visitor_name_remove_visitor_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='who_to_visit',
            new_name='whom_to_visit',
        ),
    ]
