# Generated by Django 5.0.2 on 2024-03-23 14:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates_app', '0001_initial'),
        ('organisations_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('instructions', models.TextField()),
                ('total_marks', models.IntegerField()),
                ('passing_marks', models.IntegerField()),
                ('questions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidates', models.ManyToManyField(blank=True, null=True, related_name='examinations', to='candidates_app.candidate')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='organisations_app.organisation')),
            ],
        ),
    ]
