# Generated by Django 5.0.2 on 2024-03-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations_app', '0002_alter_organisation_id_alter_organisationadmin_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='id',
            new_name='idd',
        ),
        migrations.RenameField(
            model_name='organisationadmin',
            old_name='id',
            new_name='idd',
        ),
    ]
