# Generated by Django 5.0.2 on 2024-03-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates_app', '0001_initial'),
        ('organisations_app', '0002_examination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='examinations', to='candidates_app.candidate'),
        ),
    ]
