# Generated by Django 5.0.2 on 2024-03-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations_app', '0004_alter_examination_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
