# Generated by Django 5.0.2 on 2024-03-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations_app', '0005_examination_end_time_examination_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='questions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
