# Generated by Django 5.0.2 on 2024-03-31 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations_app', '0006_alter_examination_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='draft', max_length=100),
        ),
    ]
