# Generated by Django 5.0.2 on 2024-04-16 17:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates_app', '0004_remove_candidate_exam_remove_candidate_exam_number'),
        ('organisations_app', '0008_organisation_active_organisationcomplain'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_exams', to='candidates_app.candidate')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_exams', to='organisations_app.examination')),
            ],
        ),
    ]
