# Generated by Django 5.0.2 on 2024-05-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations_app', '0010_candidateexam_candidate_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationcomplain',
            name='messages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
