# Generated by Django 5.0.2 on 2024-05-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations_app', '0011_organisationcomplain_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateexam',
            name='status',
            field=models.CharField(choices=[('admitted', 'Admitted'), ('not_admitted', 'Not_admitted')], default='not_admitted', max_length=100),
        ),
    ]
