# Generated by Django 5.0.2 on 2024-05-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations_app', '0012_candidateexam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateexam',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examination',
            name='auto_grade',
            field=models.BooleanField(default=False),
        ),
    ]
