# Generated by Django 5.0.2 on 2024-09-23 19:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates_app', '0005_alter_candidate_user'),
        ('organisations_app', '0014_candidateexam_admitted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateexam',
            name='candidate_answers',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='candidates',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='questions',
        ),
        migrations.AddField(
            model_name='candidateexam',
            name='exam_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateexam',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateexam',
            name='status',
            field=models.CharField(choices=[('admitted', 'Admitted'), ('not_admitted', 'Not_admitted')], default='not_admitted', max_length=20),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('multiple_select', 'Multiple Select'), ('true_false', 'True False'), ('essay', 'Essay'), ('fill_in_the_blank', 'Fill in the Blank')], default='multiple_choice', max_length=100)),
                ('options', models.JSONField(blank=True, default=list, null=True)),
                ('correct_answer', models.JSONField(default=dict)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='organisations_app.examination')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.JSONField(blank=True, default=dict, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='candidates_app.candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='organisations_app.question')),
            ],
        ),
    ]
